package com.notronix.lw.model;

public enum FilterName {
    General,
    SKU,
    Title,
    RetailPrice,
    PurchasePrice,
    Tracked,
    Barcode,
    VariationGroupName,
    Available,
    MinimumLevel,
    InOrder,
    StockLevel,
    StockValue,
    Due,
    BinRack,
    Category,
    ChannelSKU,
    SupplierCode,
    eBayId,
    AmazonASIN,
    Image,
    ExtendedProperty,
    ExtendedPropertyName,
    Channel,
    CreatedDate,
    ModifiedDate,
    SerialNumberScanRequired,
    BatchNumberScanRequired,
    BatchType,
    BatchNumber
}
